// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetCovid19ReportDataParams creates a new GetCovid19ReportDataParams object
// no default values defined in spec.
func NewGetCovid19ReportDataParams() GetCovid19ReportDataParams {

	return GetCovid19ReportDataParams{}
}

// GetCovid19ReportDataParams contains all the bound params for the get covid19 report data operation
// typically these are obtained from a http.Request
//
// swagger:parameters getCovid19ReportData
type GetCovid19ReportDataParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetCovid19ReportDataParams() beforehand.
func (o *GetCovid19ReportDataParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
