---
  swagger: "2.0"
  info:
    version: "1.0.0"
    title: "Provide updated report about covid19 cases in Brazil"
  paths:
    /covid19:
      get:
        operationId: "getCovid19ReportData"
        produces:
          - "application/json"
        responses:
          "200":
            description: "Up to date data about covid19 in Brazil"
            schema:
              $ref: "#/definitions/Response"
          default:
            description: "unexpected error"
            schema:
              $ref: "#/definitions/ErrorModel"
  definitions:
    ErrorModel:
      type: "object"
      required:
        - "code"
        - "message"
      properties:
        code:
          type: "integer"
          format: "int32"
        message:
          type: "string"
    Response:
      type: "object"
      properties:
        confirmed:
          type: integer
        deceased:
          type: integer
        recovered:
          type: integer
        updatedAt:
          type: string
          format: date-time
