// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Provide updated report about covid19 cases in Brazil",
    "version": "1.0.0"
  },
  "paths": {
    "/covid19": {
      "get": {
        "produces": [
          "application/json"
        ],
        "operationId": "getCovid19ReportData",
        "responses": {
          "200": {
            "description": "Up to date data about covid19 in Brazil",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorModel": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Response": {
      "type": "object",
      "properties": {
        "confirmed": {
          "type": "integer"
        },
        "deceased": {
          "type": "integer"
        },
        "recovered": {
          "type": "integer"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "swagger": "2.0",
  "info": {
    "title": "Provide updated report about covid19 cases in Brazil",
    "version": "1.0.0"
  },
  "paths": {
    "/covid19": {
      "get": {
        "produces": [
          "application/json"
        ],
        "operationId": "getCovid19ReportData",
        "responses": {
          "200": {
            "description": "Up to date data about covid19 in Brazil",
            "schema": {
              "$ref": "#/definitions/Response"
            }
          },
          "default": {
            "description": "unexpected error",
            "schema": {
              "$ref": "#/definitions/ErrorModel"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "ErrorModel": {
      "type": "object",
      "required": [
        "code",
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "Response": {
      "type": "object",
      "properties": {
        "confirmed": {
          "type": "integer"
        },
        "deceased": {
          "type": "integer"
        },
        "recovered": {
          "type": "integer"
        },
        "updatedAt": {
          "type": "string",
          "format": "date-time"
        }
      }
    }
  }
}`))
}
